# 数据库连接
jdbcUrl=jdbc:mysql://localhost:3306/db05?useSSL=false&serverTimezone=UTC
username=root
password=1234
driverClassName=com.mysql.cj.jdbc.Driver

# 连接池基本配置
minimumIdle=5
maximumPoolSize=10
connectionTimeout=30000
idleTimeout=600000
maxLifetime=1800000
connectionTestQuery=SELECT 1